### ISSUE TITLE
BNO country name conflicts with JH CSSE

### ISSUE THREAD

**Issue by jaryaman** [pr3d4t0r/COVIDvu#121]
Countries for which the BNO patch has a name conflict with JH CSSE

- UK
- South Korea
- Hong Kong
-  Czech Republic
- Gibraltar
- Macau
- Palestine
- Taiwan

This causes the country to appear as a single time point, rather than a time series.

**Comment by pr3d4t0r** [comment]
Hi!

Homologized:

- United Kingdom
- Czechia
- Taiwan

These other territories/countries do not exist in the master, and they appear as stand-alone, current day blips in the published JSON file:

- Gibraltar
- Hong Kong
- Macau
- Palestine
- Vatican City

They all have the same thing in common:  some countries in the world consider them independent nations, others consider them part of a  country (e.g. Hong Kong: China, Palestine: Israel).

I left them as blips for now.  This may get fixed with the Wikipedia source, when it becomes the ground truth.

**Comment by pr3d4t0r** [comment]
See the pull request.  Busy day here.

**Comment by jaryaman** [comment]
Hi @pr3d4t0r! 

The homologised countries don't appear to currently be in the countries list at all right now? I can't see

- UK
- Czechia
- Taiwan

in there...

**Comment by pr3d4t0r** [comment]
@jaryaman - Hola.

The ticket and merge are complete -- the names are homologized against the _ground truth_, the CSSE files and the original JSON we generate from them in `covidvu.vujson`.  Here's proof that the names are correct:

https://github.com/pr3d4t0r/COVIDvu/blob/master/work/experiments/virustrack_live-validation-tests.ipynb

@kinabalu is aware of the issue, I'm opening a separate UI ticket for him now.
