### ISSUE TITLE
Add trend / regression lines

### ISSUE THREAD

**Issue by jtdavies** [pr3d4t0r/COVIDvu#252]
When plotting log(confirmed / deaths) against the date there is a strong correlation. The slope gives the current acceleration rate. The financial Times plots this nicely every date to show how counties are doing. They use a daily rate of 33% which is 0.124 on a log scale.
![Screenshot 2020-03-22 at 19 08 28](https://user-images.githubusercontent.com/79970/77267717-6a74ed80-6c9b-11ea-9147-cc799e2f546a.png)

**Comment by pr3d4t0r** [comment]
@jtdavies - Agreed.  We are already looking at that -- here's from our morning planning meeting:

<img src='http://i.imgur.com/KwLek9v.png'>

Thanks for this and the other suggestions.  We're working on them.

**Comment by pr3d4t0r** [comment]
One thing:  we aren't 100% sure of the death rates in China because, China.  Via [Foreign Policy Insider](https://foreignpolicy.com/2020/02/19/china-coronavirus-figures-reliable-communist-party-politics-xi-jinping-quarantine-hubei/) - they may be deflated for the public and the current actual rate is higher.

**Comment by pr3d4t0r** [comment]
@jaryaman - Have a look -- thoughts?

**Comment by jtdavies** [comment]
Look at the maths though, if China had hidden bodies and the numbers were wrong they’d be having a lot of bodies to hide by now.
Frankly the Chinese figures are probably a lot more accurate than the US.

**Comment by jaryaman** [comment]
@pr3d4t0r @jtdavies yes, I think this is great visualization. The only difference between what we are planning on doing in #237 & #228 is that this plot starts the clock from the 10th death (or 100th confirmed case) rather than putting everything on "date" as the horizontal axis.

There's an argument that simplicity is king here, if we're appealing to regular people rather than geeks, and starting the clock at the 10th death _might_ confuse people. If we add too many buttons for changing the way to visualize the data, we also run the risk of confusing people.

My intuition is to have a simple switch to go from linear to log, as per #237 & #228 and leave it at that, but very willing to be persuaded otherwise! I like the visualization!

**Comment by mato** [comment]
+1 for adding the ability to plot trend lines. In case you don't know about this site, see http://nrg.cs.ucl.ac.uk/mjh/covid19/ for examples of someone doing it manually.

(And keep up the good work, I like your site and visualisations. Thank you!)

**Comment by pr3d4t0r** [comment]
Another request via Bart, Jeff Bodin, others.  Let's get this one done next.
