### ISSUE TITLE
NL data feed wanted

### ISSUE THREAD

**Issue by zohaad** [pr3d4t0r/COVIDvu#311]
@pr3d4t0r 

We, from [gewoon mensen die mensen willen helpen](https://www.gewoonmensendiemensenwillenhelpen.nl/), would like to request an NL data feed.

**Comment by loekj** [comment]
Cases and deaths, by day. With granularity of provinces if available (nice to have).

**Comment by pr3d4t0r** [comment]
@loekj - Happy to work on this when the data sources are normalized upstream from us.  The JH CSSE feed lacks province/regional data from Nederlands, and has a bunch of misspellings for the extended territoris (e.g. Sint Marten vs Saint Marten).  We're working with a commercial provider to provide us a better, more accurate feed and we'll figure how to open the API for you at that point.  We'll update this ticket and start work on this once we're sure that we can access reliable data.

If, on the other hand, you have a reliable .nl data source API that we can use, then we'd be delighted to include its output and run our analysis tools on it, so that it'll appear on the EU / NL dashboards.

Please let us know your thoughts - pr3d

**Comment by loekj** [comment]
Thank you @pr3d4t0r , 
I'll look for a better data source in the meantime. Would it be possible to already open-up the `JH CSSE` data source for now?

**Comment by pr3d4t0r** [comment]
Notes for later:  https://en.wikipedia.org/wiki/Template:2019%E2%80%9320_coronavirus_pandemic_data/Netherlands_medical_cases

**Comment by pr3d4t0r** [comment]
@loekj - We use the same data sources as everyone else, and we need to fix the screw ups introduced by the data format change.  Here's the input:  https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data

We have a whole number of things that we do to the data to ensure accuracy, and those processes are in review so we can guarantee data integrity/confidence.  Learn more here:

**Comment by pr3d4t0r** [comment]
Have a look at the _Download CSV_ button that we added per country detailed panel.  That may do the job that you need in the short term, until you guys figure out what you need.  Let me know here or in #R-Finance.

Thanks!

pr3d
