### ISSUE TITLE
Remove all theano / BLAS warnings in mini lab 

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#348]
Hi Juvid!

We need to do this in the mini lab, add the appropriate libraries, etc. to the Dockerfile after you install with `apt-get`, and/or to the Makefile if `conda` or `pip` are required.  The mini lab config is also a template for the on-the-metal server.  Thanks!

**Comment by jaryaman** [comment]
@pr3d4t0r the only warning currently displaying on the mini-lab is 
```
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
```

I'm confused because the [intel documentation](https://software.intel.com/en-us/articles/installing-the-intel-distribution-for-python-and-intel-performance-libraries-with-pip-and) states that
```
pip install mkl
```
should be sufficient for getting `mkl` to work. So I guess `conda install mkl-service` is doing some extra magic. In #347 you say that we need to get this working independently of Conda. I might need your support to figure this out. 

Useful documentation I have found for when we try to do this

- https://docs.anaconda.com/mkl-service/ -- so this creates a module which exposes some of the functions which come with mkl. I think it's a Conda-only thing. Maybe we need to just grab the source for this and install it ourselves?

- https://software.intel.com/en-us/get-started-with-mkl-for-linux
- https://software.intel.com/en-us/articles/how-to-get-intel-mkl-ipp-daal
- https://software.intel.com/en-us/articles/installing-the-intel-distribution-for-python-and-intel-performance-libraries-with-pip-and
- https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo

**Comment by jaryaman** [comment]
By the way, this is what Conda does when I install `mkl-service` on my WSL kludge-tastic environment
![image](https://user-images.githubusercontent.com/7837158/77752671-e9fa1800-701f-11ea-9ef5-bcd91534fe4f.png)


Importing `mkl` seems to do a lot of stuff

![image](https://user-images.githubusercontent.com/7837158/77752803-2a599600-7020-11ea-957b-15dd8cd08fbc.png)
