### ISSUE TITLE
Disable the Rate button when Average is deployed

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#575]
Please disable the Rate button when Average is deployed.  It's not very meaningful since people in general can't figure out how to read it.  The 7-day average, on the other hand, seems to be the killer app.  We might even want to plan pushing that all the way to the front Dashboard, as the default view when the user opens and sees their default country.

**Comment by kinabalu** [comment]
I love the Average button, but Rate actually gets used. in the last 7 days it was used 151 times according to the google analytics. What about swapping the buttons so that Average shows up before the Rate button?

The 7-day average will show up on the homepage, if we want to open it up for a specific graph, let's figure that out.

**Comment by kinabalu** [comment]
For now, we're keeping the Rate button and we swapped it with New Cases in the order so it shows up prior. Please re-open if you think we should re-address and consider removing the Rate button. I know we'll be revising some of the graph view for Rate soon with #582
