### ISSUE TITLE
Fix COVIDvu Notebooks crash on refreshdata

### ISSUE THREAD

**Issue by pr3d4t0r** [pr3d4t0r/COVIDvu#76]
Steps to recreate:

1. Open the Notebook
1. Execute the cell, `%%bash ./refreshdata`

**Comment by jaryaman** [comment]
This may well be a Windows thing, in which case you have bigger fish to fry. But in case this is a wider issue:

From Jupyter:

![image](https://user-images.githubusercontent.com/7837158/76804913-65182e80-67d5-11ea-87bb-752e9f3a1a10.png)

From WSL:
![image](https://user-images.githubusercontent.com/7837158/76804935-72351d80-67d5-11ea-8083-edf1e51693cc.png)

**Comment by jaryaman** [comment]
This is expected output -- needs a valid configuration file for `refreshdata`

**Comment by jaryaman** [comment]
Problem seems to have popped up again
![image](https://user-images.githubusercontent.com/7837158/77415893-06e1e180-6dbb-11ea-84b7-4110e722c352.png)

**Comment by dlwhitehurst** [comment]
@jaryaman I'm on a macbook using the docker lab and I'm getting this issue as well. I'll comment again if I figure this out.

**Comment by dlwhitehurst** [comment]
I just realized that not just anyone can run the Bash script "refreshdata" because refreshdata.config needs to be created from refreshdata.config.SAMPLE. This means that I get the  CONTAINER_SIG_FILE because I don't have the AWS credentials. @pr3d4t0r @jaryaman what would be the option in the event the AWS creds aren't available to the public? I can modify the /work COVIDvu notebook with alternate sources, if I know how to model the Amazon S3 (assuming) data.

**Comment by jaryaman** [comment]
@dlwhitehurst yes I haven't gotten around to fixing this, good question. In the meantime, just do
```
cd ./work/COVID-19
git pull
```
and then run the rest of the cells.
